title: "Neomadic Scholar"
description: "We specialize in providing expert counselling, test preparations and meticulous processing for abroad study aspirants of Nepal."
images: 
  - "images/hero-image.png"

logo: "logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  dribbble: "#"
  instagram: "#"
  facebook: "#"
  twitter: "#"

location:
  - "Sankhamul Marga (beside Columbus Campus premises) - New Baneshwor, Kathmandu"

contact:
  - "info@neomadic.com.np"
  - "+977 984-7558458"
  - "+977 1 5925776"

copyright: "© 2026 Neomadic Scholar Education Consultancy Pvt. Ltd."